chore: revert to build pre-commit (#1587)
Currently docker builds work only outside of the dev container in dls
workstation. So reverting this change

```
error: Failed to run hook `helm-docs-container`
  caused by: Failed to run `docker run --rm --tty --user 0:0 --init --volume /workspaces/blueapi:/src:rw,Z --workdir /src jnorwood/helm-docs:latest --chart-search-root=helm`
  caused by: No such file or directory (os error 2)
error: Recipe `lint` failed on line 25 with exit code 2
```